#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : libdvdread
Version  : 6.1.2
Release  : 6
URL      : file:///aot/build/clearlinux/packages/libdvdread/libdvdread-6.1.2.tar.gz
Source0  : file:///aot/build/clearlinux/packages/libdvdread/libdvdread-6.1.2.tar.gz
Summary  : Low level DVD access library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MPL-1.1
Requires: libdvdread-lib = %{version}-%{release}
BuildRequires : doxygen
BuildRequires : findutils
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
What is this all about?
-----------------------
libdvdnav is a library that allows easy use of sophisticated DVD navigation
features such as DVD menus, multiangle playback and even interactive DVD games.
All this functionality is provided through a simple API which provides the
DVD playback as a single logical stream of blocks, intermitted by special
dvdnav events to report certain conditions. The main usage of libdvdnav is a
loop regularly calling a function to get the next block, surrounded by
additional calls to tell the library of user interaction.
The whole DVD virtual machine and internal playback states are completely
encapsulated.

%package dev
Summary: dev components for the libdvdread package.
Group: Development
Requires: libdvdread-lib = %{version}-%{release}
Provides: libdvdread-devel = %{version}-%{release}
Requires: libdvdread = %{version}-%{release}

%description dev
dev components for the libdvdread package.


%package doc
Summary: doc components for the libdvdread package.
Group: Documentation

%description doc
doc components for the libdvdread package.


%package lib
Summary: lib components for the libdvdread package.
Group: Libraries

%description lib
lib components for the libdvdread package.


%package staticdev
Summary: staticdev components for the libdvdread package.
Group: Default
Requires: libdvdread-dev = %{version}-%{release}

%description staticdev
staticdev components for the libdvdread package.


%prep
%setup -q -n libdvdread
cd %{_builddir}/libdvdread

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620595145
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math -fstack-protector-strong -fzero-call-used-regs=used "
%reconfigure --enable-shared --enable-static
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1620595145
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/dvdread/bitreader.h
/usr/include/dvdread/dvd_reader.h
/usr/include/dvdread/dvd_udf.h
/usr/include/dvdread/ifo_print.h
/usr/include/dvdread/ifo_read.h
/usr/include/dvdread/ifo_types.h
/usr/include/dvdread/nav_print.h
/usr/include/dvdread/nav_read.h
/usr/include/dvdread/nav_types.h
/usr/include/dvdread/version.h
/usr/lib64/libdvdread.so
/usr/lib64/pkgconfig/dvdread.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libdvdread/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libdvdread.so.8
/usr/lib64/libdvdread.so.8.0.0

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libdvdread.a
